config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


  devise_for :tenants


  devise_for :agencies, except: [:index]
  authenticated :agency do
    root 'agencies#show'
  end


  resources :agencies, except: [:index]  do
    resources :properties, except: [:index]
  end

  resources :agents, only: [:create, :update, :edit]



  resources :properties, only: [:index, :show] do 
    resources :visits, only: [:create, :update, :destroy]
  end

  resources :properties, only: [:index, :show] do
    resources :favorites, only: [:create, :update]
  end

  resources :tenants do
    resources :favorites, only: [:index]
  end

  resources :tenants, only: [:show, :edit, :update] do
    resources :properties, only: [:index]
  end

  resources :charges, only: [:index, :create]

  resources :payments, only: [:index, :create]

  root 'payments#index'
  get 'thank_you', to: 'payments#thank_you'


  # root 'statics#index'
  get 'team' , to: 'statics#team'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

      user ||= Agency.new # guest user (not logged in)
      if user.is_a? Agency
        can :manage, Property, agency: {agency_id: user.id}
        # can :manage, Agency, {agency_id: user.id}
      end
      if user.is_a? Tenant
        can :show, Property, agency: {agency_id: user.id}
        # can :manage, Agency, {agency_id: user.id}

      end


      
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin 2.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/agency.rb
class Agency < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_many :agency_groups
  has_many :groups, through: :agency_groups
  
  has_many :agents
  has_many :properties
  
 
  validates :email, presence: true

  after_create :create_agents


  def create_agents

  	director = Agent.create(first_name: "",
  		last_name: "",
  		email: "",
  		cellphone: "",
  		position_id: 1,
  		agency_id: self.id)

  	agent = Agent.create(first_name: "",
  		last_name: "",
  		email: "",
  		cellphone: "",
  		position_id: 2,
  		agency_id: self.id)

  end

  def available_properties
    self.properties.where(is_archived: false)
  end 

end

app/models/agency_group.rb
class AgencyGroup < ApplicationRecord
  belongs_to :group
  belongs_to :agency
end

app/models/agent.rb
class Agent < ApplicationRecord
  belongs_to :position
  belongs_to :agency
  has_many :properties

end

app/models/area.rb
class Area < ApplicationRecord
	has_many :properties
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :tenant
	belongs_to :property

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :agency_groups
  has_many :agencies, through: :agency_groups

  validates :name, presence: true
end

app/models/payment_status.rb
class PaymentStatus < ApplicationRecord
  has_many :tenants
end

app/models/position.rb
class Position < ApplicationRecord
  has_many :agents

  validates :title, 
    presence: true,
    uniqueness: true
end

app/models/property.rb
class Property < ApplicationRecord
	belongs_to :agent
	belongs_to :agency
	belongs_to :area

	has_many_attached :images
	has_many :visits

	has_many :favorites
	has_many :tenants, through: :favorites

	validates :title, 
	:surface, 
	:address, 
	:room, 
	:description, 
	:price, 
	:floor, 
	:available_date, presence: true

	validates :room, numericality: { only_integer: true }
	validates :price, numericality: { only_integer: true }
	validates :surface, numericality: true
	validates :floor, numericality: { only_integer: true }
	validates :description, length: { minimum: 40 }
	validates :title, length: { minimum: 10 }

	def self.not_archived
		self.where(is_archived: false)
	end 

	def total_rent
		self.price.to_i + self.charges.to_i
	end

	def existant_fav(tenant)
		Favorite.find_by(property_id: self.id, tenant: tenant)
	end

	def requested_visits(tenant)
		self.visits.where(visit_status_id: 4, tenant: tenant)
	end

	def requested_visits_agency
		self.visits.where(visit_status_id: 4, property: self)
	end

end

app/models/status.rb
class Status < ApplicationRecord
  has_many :visits
end

app/models/tenant.rb
class Tenant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  has_many :visits
  belongs_to :payment_status

  before_validation :default_payment_status

  has_many :favorites
  has_many :properties, through: :favorites

  has_one_attached :avatar

  before_create :attach_avatar

  def default_payment_status
    self.payment_status_id ||= 1
  end

  def fav_properties
    self.favorites.where(is_liked: true)
  end

  def asked_visits
    self.visits.where(visit_status_id: 4)
  end

  def successful_rent
    self.visits.where(visit_status_id: 6)
  end

  def attach_avatar
    self.avatar.attach(io: File.open('app/assets/images/avatar.png'), filename: 'avatar.png', content_type: 'image/png')
  end

  def existant_visit(property)
    visit = Visit.find_by(property_id: property.id, tenant: self)
    if visit
      return visit
    end
  end

  def unfav(property)
    favoris = Favorite.find_by(property_id: property.id, tenant: self, is_liked: true)
    unless favoris.nil?
      favoris.update_attributes(is_liked: false)
    end
  end


  def welcome_mail
    TenantMailer.welcome_email(self).deliver_now
  end

  def requested_visits
    self.visits.where(visit_status_id: 4)
  end

  def fav_properties
    self.favorites.where(is_liked: true)
  end

  def property_fav(property)
    self.favorites.where(property: property)
  end
end

app/models/visit.rb
class Visit < ApplicationRecord

	after_save :new_visit_email_send

  belongs_to :tenant
  belongs_to :property
  belongs_to :visit_status   

 	def new_visit_email_send
  	TenantMailer.new_visit_email(self.tenant, self.property).deliver_now
  end


end

app/models/visit_status 2.rb
class VisitStatus < ApplicationRecord
  has_many :visits
end

app/models/visit_status.rb
class VisitStatus < ApplicationRecord
  has_many :visits
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/admins/_login_registrar_form.html 2.erb
<div class="viewport">
  <div class="image image-overlay" style="background-image:url(<%=asset_path('money.jpg')%>)"></div>


  <div class="container">
    <div class="row justify-content-center align-items-center vh-100">
      <div class="col-md-6 col-lg-5">
        <div class="accordion-group accordion-group-portal" data-accordion-group="">


          <!-- LOGIN -->
          <div class="accordion open" data-accordion="">
            <div class="accordion-control" data-control="">
              <h5>Connexion Admin</h5>
            </div>
            <div class="accordion-content" data-content="" style="max-height: 382px; overflow: hidden; transition: max-height 300ms ease 0s;">
              <div class="accordion-content-wrapper">
                <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                <div class="form-group">
                  <%= f.input :email,
                  required: false,
                  autofocus: true,
                  input_html: { autocomplete: "email", class: "form-control" } %>

                  <span style="opacity: 1; left: 392px; top: 151.5px; width: 19px; min-width: 19px; height: 13px; position: absolute; background-image: url(""); background-repeat: no-repeat; background-position: 0px 0px; border: none; display: inline; visibility: visible; z-index: auto;"></span>
                </div>

                <div class="form-group">
                  <%= f.input :password,
                  required: false,
                  input_html: { autocomplete: "current-password", class: "form-control"  } %>
                  <span style="opacity: 1; left: 392px; top: 249.5px; width: 19px; min-width: 19px; height: 13px; position: absolute; background-image: url(""); background-repeat: no-repeat; background-position: 0px 0px; border: none; display: inline; visibility: visible; z-index: auto;"></span></div>


                  <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>

                  <%= f.button :submit, "Se connecter", class: "btn btn-primary btn-block" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>



  </div>

app/views/admins/_login_registrar_form.html.erb
<div class="viewport">
  <div class="image image-overlay" style="background-image:url(<%=asset_path('sofa.jpg')%>)"></div>


  <div class="container">
    <div class="row justify-content-center align-items-center vh-100">
      <div class="col-md-6 col-lg-5">
        <div class="accordion-group accordion-group-portal" data-accordion-group="">

          <div class="row  p-1 mb-0 bg-orange d-flex align-items-center">
            <div class="col-12 agency-login d-flex align-items-center justify-content-center">
              Espace admin
            </div>
          </div>
          <!-- LOGIN -->
          <div class="accordion open" data-accordion="">
            <div class="accordion-control" data-control="">
              <h5>Connexion Admin</h5>
            </div>
            <div class="accordion-content" data-content="" style="max-height: 382px; overflow: hidden; transition: max-height 300ms ease 0s;">
              <div class="accordion-content-wrapper">
                <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                <div class="form-group">
                  <%= f.input :email,
                  required: false,
                  autofocus: true,
                  input_html: { autocomplete: "email", class: "form-control" } %>

                  <span style="opacity: 1; left: 392px; top: 151.5px; width: 19px; min-width: 19px; height: 13px; position: absolute; background-image: url(""); background-repeat: no-repeat; background-position: 0px 0px; border: none; display: inline; visibility: visible; z-index: auto;"></span>
                </div>

                <div class="form-group">
                  <%= f.input :password,
                  required: false,
                  input_html: { autocomplete: "current-password", class: "form-control"  } %>
                  <span style="opacity: 1; left: 392px; top: 249.5px; width: 19px; min-width: 19px; height: 13px; position: absolute; background-image: url(""); background-repeat: no-repeat; background-position: 0px 0px; border: none; display: inline; visibility: visible; z-index: auto;"></span></div>


                  <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>

                  <%= f.button :submit, "Se connecter", class: "btn btn-orange btn-block" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>



  </div>

app/views/admins/shared/_error_messages.html 2.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html 2.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>