config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


  devise_for :tenants


  devise_for :agencies, except: [:index]
  authenticated :agency do
    root 'agencies#show'
  end


  resources :agencies, except: [:index]  do
    resources :properties, except: [:index]
  end

  resources :agents, only: [:create, :update, :edit]



  resources :properties, only: [:index, :show] do 
    resources :visits, only: [:create, :update, :destroy]
  end

  resources :properties, only: [:index, :show] do
    resources :favorites, only: [:create, :update]
  end

  resources :tenants do
    resources :favorites, only: [:index]
  end

  resources :tenants, only: [:show, :edit, :update] do
    resources :properties, only: [:index]
  end

  resources :charges, only: [:index, :create]

  resources :payments, only: [:index, :create]

  root 'payments#index'
  get 'thank_you', to: 'payments#thank_you'


  # root 'statics#index'
  get 'team' , to: 'statics#team'

end

app/models/property.rb
class Property < ApplicationRecord
	belongs_to :agent
	belongs_to :agency
	belongs_to :area

	has_many_attached :images
	has_many :visits

	has_many :favorites
	has_many :tenants, through: :favorites

	validates :title, 
	:surface, 
	:address, 
	:room, 
	:description, 
	:price, 
	:floor, 
	:available_date, presence: true

	validates :room, numericality: { only_integer: true }
	validates :price, numericality: { only_integer: true }
	validates :surface, numericality: true
	validates :floor, numericality: { only_integer: true }
	validates :description, length: { minimum: 40 }
	validates :title, length: { minimum: 10 }

	def self.not_archived
		self.where(is_archived: false)
	end 

	def total_rent
		self.price.to_i + self.charges.to_i
	end

	def existant_fav(tenant)
		Favorite.find_by(property_id: self.id, tenant: tenant)
	end

	def requested_visits(tenant)
		self.visits.where(visit_status_id: 4, tenant: tenant)
	end

	def requested_visits_agency
		self.visits.where(visit_status_id: 4, property: self)
	end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  before_action :authenticate_agency!, except: [:index, :show]

  def index
    @properties = Property.all
    @last_property = Property.last
    @last_date = ((Time.now - @last_property.created_at)/60/60/24).to_i

    @tenant = current_tenant
    @tenant ||= Tenant.new
    @asked_visits = @tenant.requested_visits

    @favorite = Favorite.new

    @tenant_id = params[:tenant_id]


  end

  def show
    @properties = Property.all
    @property = Property.find(params[:id])

    @areas = Area.all
    @tenant = current_tenant
    @tenant ||= Tenant.new

    @favorite = @tenant.property_fav(@property).last
    @asked_visits_tenants = @property.requested_visits_agency
    @asked_visits = @tenant.requested_visits

    @agency = @property.agency
  end

  def new
  	@agency = Agency.find(params[:agency_id])
    @property = Property.new
  end

  def create
  	@property = Property.new(property_params)
    @property.images.attach(params[:property][:images])
    @property.agency_id = params[:agency_id]
    @property.agent_id = 1
    @property.area = Area.find_by(name: params[:area])


    if @property.save
      flash[:success] = "Votre bien a été créé"
      redirect_to agency_path(current_agency)
    else
      flash[:danger] = @property.errors.messages
      redirect_back(fallback_location: root_path)
    end
  end

  def edit

  end

  def update
    @property = Property.find(params[:id])
    @agency = Agency.find(params[:agency_id])

    if @property.update(agency_property_params)
      flash[:success] = "Votre bien a été mis à jour"
      redirect_to agency_property_path(@agency,@property)
    else
      flash[:danger] = @property.errors.messages
      redirect_to agency_property_path(@agency,@property)
    end
  end


  def destroy
    @property = Property.find(params[:property_id])
    if @property.update(is_archived: true)
      flash[:success] = "Votre bien a été archivé"
      redirect_to agency_path(current_agency)
    else
      flash[:danger] = @property.errors.messages
      redirect_to agency_path(current_agency)
    end
  end



  private

  def agency_property_params
    params.require("/agencies/#{@agency.id}/properties/#{@property.id}").permit(:title, :price, :surface, :description, :floor, :room, :available_date, :address, :charges, :agency_fees, :deposit, :furnished)
  end

  def property_params
  	params.require(:property).permit(:title, :price, :surface, :description, :floor, :room, :available_date, :address, :charges, :agency_fees, :deposit, :furnished)
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_banner_property_index_tenant.html.erb
<section class="p-3 bg-light" style="margin-top:0px;">
  <div class="image image-overlay" style="background-image:url(<%=asset_path('sofa3.jpg')%>); opacity:1; filter: blur(10px);"></div>

  <div class="container text-white"">
    <div class="row justify-content-center ">
      <div class="col-md-8 align-self-center text-center">
        <h2 class="mt-6">Visite les appartements
          <h1><span id="typed" class="text-blue"></span></h1>

          <div id="typed-strings">
            <p>en avant-première.</p>
            <p>sans aucune galère.</p>
            <p>avant tout le monde.</p>
          </div>


        </div>
      </div>
    </div>
  </section>

app/views/properties/_card_property.html.erb
<div class="col-xs-12 col-md-6 col-lg-4 p-1">
	<div class="card">
		<%= link_to property_path(property.id), class: "card-img-container" do %>
		<img class="card-img-top" src="<%=asset_path(image_path(main_app.url_for(property.images.first)))%>" alt="Property image">
		<div class="card-header  d-flex flex-column justify-content-between">
			<div class="d-flex justify-content-end">
				<% if tenant_signed_in? %>
					<%if property.existant_fav(current_tenant)%>
						<%= form_tag property_favorite_path(property.id, property.existant_fav(current_tenant).id), method: 'put', remote: true, id: "btn-update-#{property.id}" do%>
							<%= button_tag(type: "submit", class: "btn-invisible") do %>
							<span class="circle-fav d-flex justify-content-around align-items-center"><i class="fas fa-heart text-<%= property.existant_fav(current_tenant).is_liked ? "orange" : "light" %>" id="fav-<%=property.id %>"></i></span>
							<% end %>
						<% end%>
					<% else %>
						<%= form_tag property_favorites_path(property.id), method: 'create', id: "btn-create-#{property.id}", remote: true do%>
							<%= button_tag(type: "submit", class: "btn-invisible") do %>
							<span class="circle-fav d-flex justify-content-around align-items-center"><i class="fas fa-heart text-light" id="fav-<%=property.id %>"></i></span>
							<% end %>
						<% end%>
					<% end %>
				<% end %>
			</div>
			<div><h5 class="card-title"><%= property.title %></h5></div>
		</div>
		<% end %>
		<div class="card-body">
			<div class="row mb-2 d-flex justify-content-around" >
				<div class="text-muted" style="font-weight: 500"><i class="text-primary fas fa-coins mr-1"></i><%= property.total_rent %> € C.C.</div>
				<div class="text-muted" style="font-weight: 500"><i class="text-primary fas fa-arrows-alt-h mr-1"></i><%= property.surface %> m&#xB2;</div>
				<div class="text-muted" style="font-weight: 500"> <i class="text-primary fas fa-map-marker-alt mr-1"></i><%= property.area.zipcode %></div>
			</div>
			<div class="row d-fex justify-content-around flex-wrap mb-0">
				<div class="row d-fex justify-content-around  flex-wrap mb-2">
					<div class="item-property p-1 m-1 mb-0 flex-wrap"> <%=property.floor%> <sup>e</sup> étage</div>
					<div class="item-property p-1 m-1 mb-0 flex-wrap"> <%=property.room%> pièces</div>
				</div>
				<div class="justify-content-around flex-wrap">
					<%= link_to "Voir plus", property_path(property.id), class: "btn btn-primary" %> 
				</div>
			</div>
		</div>
	</div>
</div>

app/views/properties/_index_properties_tenant.html.erb
<div class="row mb-4">
<% visits.each do |visit| %>
	<div class="col-xs-12 col-md-6 col-lg-4 p-1">
		<div class="card">
			<%= link_to property_path(visit.property.id), class: "card-img-container" do %>
			<img class="card-img-top" src="<%=asset_path(image_path(main_app.url_for(visit.property.images.first)))%>" alt="Property image">
			<div class="card-header  d-flex flex-column justify-content-between">
				<div class="d-flex justify-content-end">
				</div>
				<div>
					<h5 class="card-title"><%= visit.property.title %></h5>
				</div>
			</div>
			<% end %>
			<div class="card-body">
				<div class="row mb-2 d-flex justify-content-around" >
					<div class="text-muted" style="font-weight: 500"><i class="text-primary fas fa-coins mr-1"></i><%= visit.property.total_rent %> € C.C.</div>
					<div class="text-muted" style="font-weight: 500"><i class="text-primary fas fa-arrows-alt-h mr-1"></i><%= visit.property.surface %> m&#xB2;</div>
					<div class="text-muted" style="font-weight: 500"> <i class="text-primary fas fa-map-marker-alt mr-1"></i><%= visit.property.area.zipcode %></div>
				</div>

				<div class="row d-fex justify-content-around flex-wrap mb-0">
					<div class="row d-fex justify-content-around  flex-wrap mb-0">
						<div class="item-property p-1 m-1 mb-0 flex-wrap"> <%=visit.property.floor%> <sup>e</sup> étage</div>
						<div class="item-property p-1 m-1 mb-0 flex-wrap"> <%=visit.property.room%> pièces</div>
					</div>
					<div class="d-flex justify-content-around flex-wrap">
						<%if visit.visit_status_id == 4 %>
						<p class="text-center">Le gestionnaire du bien va revenir vers vous afin de convenir d'un rendez-vous</p>
							<%= form_tag property_visit_path(visit.property, visit), method: 'delete' do %>
								<%= hidden_field_tag :visit_id, visit.id %>
								<%= submit_tag 'Annuler ma demande', class: 'btn btn-light' %>
							<% end %>
						<%else%>
							<%= link_to 'Visiter', property_visits_path(visit.property.id), class: 'btn btn-blue', method: 'create' %>
							<p><br> Une fois que vous aurez validé votre demande, le gestionnaire du bien reviendra vers vous afin de convenir d'un rendez-vous</p>
						<%end%>
					</div>
				</div>
			</div>
		</div>
	</div>

<%end%>
</div>

app/views/properties/_properties_show_steps.html.erb
<section class="section-lg">
      <div class="container">
        <div class="row justify-content-center text-center text-lg-left">

	          <div class="accordion-group accordion-group-steps" data-accordion-group="">
	            <div class="accordion open accordion-padding" data-accordion="">
	              <div class="accordion-control" data-control="">
	                <h2>Découvrez nos appartements en avant première</h2>
	              </div>
	              <div class="accordion-content">
	                <div class="accordion-content-wrapper">
	                  <p>Mettez-les en favori <i class="ml-1 fas fa-heart text-orange"></i></p>
	                </div>
	              </div>
	            </div>
              <div class="accordion accordion-padding" data-accordion="">
               <div class="accordion-control" data-control="">
                 <h2>Renseignez votre empreinte bancaire</h2>
               </div>
               <div class="accordion-content">
                 <div class="accordion-content-wrapper">
                   <p>Si vous ne trouvez pas votre appartement avec Ding Dong, vous ne serez pas débité.<i class="ml-1 fas fa-credit-card text-orange"></i> </p>
                 </div>
               </div>
             </div>
	            <div class="accordion accordion-padding" data-accordion="">
	              <div class="accordion-control" data-control="">
	                <h2>Inscrivez-vous aux visites de vos appartements préférés</h2>
	              </div>
	              <div class="accordion-content">
	                <div class="accordion-content-wrapper">
	                  <p>Nous vous recontacterons dans les plus brefs délais<i class="ml-1 fas fa-calendar-check mr-1 text-orange"></i> </p>
	                </div>
	              </div>
	            </div>
	            <div class="accordion accordion-padding" data-accordion="">
	              <div class="accordion-control" data-control="">
	                <h2>Visitez avant tout le monde</h2>
	              </div>
	              <div class="accordion-content">
	                <div class="accordion-content-wrapper">
	                  <p>Comme promis, pas plus de 10 visiteurs pour un appart<i class="ml-1 fas fa-users text-orange"></i> </p>
	                </div>
	              </div>
	            </div>
              <div class="accordion accordion-padding" data-accordion="">
	              <div class="accordion-control" data-control="">
	                <h2>Vous êtes retenu pour l'appartement !</h2>
	              </div>
	              <div class="accordion-content">
	                <div class="accordion-content-wrapper">
	                  <p>Vous recevez une réponse dans la semaine et vous serez débité de 99€<i class="ml-1 fas fa-key text-orange"></i> </p>
	                </div>
	              </div>
	            </div>
	          </div>
		</div>
	</div>
</section>

app/views/properties/_property_show_tenant_banner.html.erb
<section class="p-0" >
  <% first_property = @property.images.first %>
      <div class="container pl-4 pr-4">
          <div class="row">
            <div class="col-12 p-0">
              <h2 class="mt-10 text-black"><%=property.title%></h2>
            </div>
          </div>




          <div class="row">
            <div class="col-lg-6 col-sm-12 p-0">
                	<h5 class="text-black"><i class="fas fa-coins mr-1 text-primary"></i> <%=property.total_rent%> € CC
                	</h5>
                	<h5 class="text-black"><i class="fas fa-arrows-alt-h mr-1 text-primary"></i> <%=property.surface%> m<sup>2</sup>
                	</h5>
                	<h5 class="text-black"><i class="fas fa-map-marker-alt mr-1 text-primary"></i> <%=property.area.zipcode%>
                	</h5>
            </div>

            <div class="col-lg-6 col-sm-12 p-0">


                  <% if @property.visits.find_by(tenant: current_tenant, property_id: params[:id], visit_status_id: 4) %>
                      <p> Vous avez déjà demandé la visite </p>
                  <% else %>

                    <% if tenant_signed_in? %>
                      <%= render 'layouts/modal_btn', property: @property %>
                      <%= render 'layouts/modal_description' %>
                    <% else %>

                        <div class="row">
                          <div class="col mb-3">
                              <div class="col-lg-6 col-sm-12 p-0 mb-1">
                            <%= link_to 'Enregistrer',  new_tenant_session_path, class: 'btn btn-outline-orange'%>                              </div>
                              <div class="col-lg-6 col-sm-12 p-0">
                                <%= link_to 'Demander une visite',  new_tenant_session_path, class: 'btn btn-outline-primary'%>
                              </div>
                          </div>
                        </div>

                    <% end %>
                  <% end %>




            </div>
          </div>



          <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" style="max-width: 1000px;" role="document">
              <div class="modal-content">
                <div class="modal-header justify-content-end">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" class="icon-x"></span>
                  </button>
                </div>
                <div class="modal-body text-center">


                </div>
              </div>
            </div>
          </div>

      </div>
</section>

app/views/properties/_property_show_tenant_description.html.erb
<div class="container pl-4 pr-4">
  <div class="row justify-content-around">
    <div class="col-lg-4 mr-3 p-0">
      <span class="text-primary"> Infos pratiques </span> <br> <br>

      <div class="mb-1"><i class="fas fa-map-marker-alt mr-1 text-primary"></i> Adresse :
        <span class="text-muted"> <%=property.address%> </span>
      </div>

      <div class="mb-3"><i class="fas fa-calendar-alt mr-1 text-primary"></i> Disponibilité :
        <span class="text-muted">  <%=property.available_date.to_date%>  </span>
      </div>

      <span class="text-primary">L'appartement</span> <br> <br>
      <div class="mb-1"><i class="fas fa-arrows-alt-h mr-1 text-primary "></i> Surface :
        <span class="text-muted"> <%=property.surface%> m2</span>
      </div>
      <div class="mb-1"><i class="fas fa-bed mr-1 text-primary"></i> Pièces :
        <span class="text-muted"> <%=property.room%> </span>
      </div>

      <div class="mb-3"><i class="fas fa-hiking mr-1 text-primary"></i> Etage :
        <span class="text-muted"> <%=property.floor%> ème</span>
      </div>

      <span class="text-primary">Conditions financières</span> <br> <br>
      <div class="mb-1"><i class="fas fa-coins mr-1 text-primary"></i> Loyer C.C. / Mois :
        <span class="text-muted"> <%=property.total_rent%> €</span>
        <div class="text-muted"> > Dont <%= property.charges %> € de charges </div>
      </div>

      <div class="mb-1"><i class="fas fa-money-check mr-1 text-primary"></i>Honoraires de location :
        <span class="text-muted"> <%= property.agency_fees %> €</span>
        <div class="text-muted"> > Et <%= property.deposit %> € de dépôt de garantie </div>
      </div>

      <div class="mb-3"><i class="fas fa-bell mr-1 text-primary"></i> Honoraires Ding Dong :
        <span class="text-muted"> 99€ </span>
        <div class="text-muted"> > Uniquement si vous louez l'appartement </div>

      </div>

    </div>
    <div class="col-lg-7 p-0">
      <span class="mr-1 text-primary">Description du bien <br> <br> </span>
        <div class="text-muted text-justify"><%=property.description%></div>
      </div>
    </div>

  </div>

  <div class="row" style="justify-content: flex-end;">
    <div class="card-meta font-weight-light mr-1">Ajouté le : <%=property.updated_at.to_date%>
    </div>
  </div>

</div>

app/views/properties/index.html.erb
<%= render 'layouts/navbar_light' %>
<%= render 'banner_property_index_tenant', property: Property.first %>



<div class="tab-content m-3" >
	<div class="container">


<% if @tenant_id %>
		<h3 class="mt-4 mb-3">Demandes de visites</h3>

		<% if @asked_visits.size > 0 %>
			<%= render 'properties/index_properties_tenant', visits: @asked_visits %>
		<% else %>
		<p>Oh oh, vous n'avez fait aucune demande de visite pour le moment</p>
		<% end %>
		<div class="row mb-4 pl-2">
		<%= link_to "Continuer mes recherches", properties_path %>
		</div>
	</div>
</div>
<%= render 'layouts/footer' %>


<% else %>

<div class="row mb-4 d-flex align-items-end mt-4">
	<h3 class="m-0 p-0">Notre dernière annonce</h3> &nbsp;&nbsp;
	<lead class="text-orange">publiée il y a  <%= @last_date%> jour(s)</lead>
</div>

<div class="row d-flex justify-space-around align-items-center">
	
	<div class="col-xs-12 col-md-8">
		<img class="main-property-img" src="<%=asset_path(image_path(main_app.url_for(@last_property.images.first)))%>" alt="Property image">
	</div>

	<div class="col-xs-12 col-md-4 d-flex flex-column justify-content-between">
		
		<div class="col-12 mb-2">
			<h4 class="text-orange"><%= @last_property.title%></h4>
		</div>
		
		<div class="col-12 mb-2">
			<div class="text-primary" style="font-weight: 900"><i class="fas fa-coins mr-1"></i><%= @last_property.total_rent %> € C.C.</div>

			<div class="text-primary" style="font-weight: 900"><i class="fas fa-arrows-alt-h mr-1"></i><%= @last_property.surface %> m&#xB2;</div>

			<div class="text-primary" style="font-weight: 900"> <i class="fas fa-map-marker-alt mr-1"></i><%= @last_property.area.zipcode %></div>
		</div>
		
		<div class="col-12">
			<%= link_to "Je fonce découvrir !", property_path(@last_property.id), class: "btn btn-primary" %> 
		</div>
			

	</div>

</div>

<div class="row mb-3 mt-4">
	<h3>Toutes les annonces (<%= @properties.size %>)</h3>
</div>
<div class="row">
	<% @properties.each do |property| %>
	<%= render 'properties/card_property', property: property %> 

	<% end %> 

</div>
</div>
</div>
<%= render 'layouts/footer' %>
<%end%>

app/views/properties/new.html.erb
<h1>Add a property</h1>


<div class="container">
	<div class="row">
			<%= form_for [@agency, @property] do |f| %>
			Titre : 
			<%= f.text_field :title %> <br><br>
			Price : 
			<%= f.text_field :price %> <br><br>
			Surface : 
			<%= f.text_field :surface %> <br><br>
			Description : 
			<%= f.text_area :description %> <br><br>
			Etage : 
			<%= f.text_field :floor %> <br><br>
			Nombre de pièces : 
			<%= f.number_field :room %> <br><br>
			Disponibilité : 
			<%= f.datetime_select :available_date %> <br><br>
			Adresse : 
			<%= f.text_area :address %> <br><br>
			Image :
			<%= f.file_field :images, multiple: true %> <br><br>

			<%= submit_tag("Créer", id: "button", class: "Test", name: "submit") %>

			<% end %>
					
	</div>

</div>

app/views/properties/show.html.erb
 <%if agency_signed_in? %>

<%= render 'layouts/navbar' %>

<%= render 'layouts/property_show_agency_banner', property: @property, areas: @areas %>
<%= render 'layouts/property_show_visitors', visits: @asked_visits_tenants %>
<%= render 'layouts/property_show_description', agency: @agency, property: @property%>
<%= render 'layouts/property_show_carroussel', property: @property %>

<%= render 'layouts/footer' %>

<% else %>

<%= render 'layouts/navbar' %>
<%= render 'property_show_tenant_banner', property: @property, areas: @areas %>

<%= render 'layouts/property_show_carroussel', property: @property %>
<%= render 'property_show_tenant_description', agency: @agency, property: @property%>
<%= render 'properties_show_steps', property: @property%>


<%= render 'layouts/footer' %>

<% end %>