config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


  devise_for :tenants


  devise_for :agencies, except: [:index]
  authenticated :agency do
    root 'agencies#show'
  end


  resources :agencies, except: [:index]  do
    resources :properties, except: [:index]
  end

  resources :agents, only: [:create, :update, :edit]



  resources :properties, only: [:index, :show] do 
    resources :visits, only: [:create, :update, :destroy]
  end

  resources :properties, only: [:index, :show] do
    resources :favorites, only: [:create, :update]
  end

  resources :tenants do
    resources :favorites, only: [:index]
  end

  resources :tenants, only: [:show, :edit, :update] do
    resources :properties, only: [:index]
  end

  resources :charges, only: [:index, :create]

  resources :payments, only: [:index, :create]

  root 'payments#index'
  get 'thank_you', to: 'payments#thank_you'


  # root 'statics#index'
  get 'team' , to: 'statics#team'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

      user ||= Agency.new # guest user (not logged in)
      if user.is_a? Agency
        can :manage, Property, agency: {agency_id: user.id}
        # can :manage, Agency, {agency_id: user.id}
      end
      if user.is_a? Tenant
        can :show, Property, agency: {agency_id: user.id}
        # can :manage, Agency, {agency_id: user.id}

      end


      
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin 2.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/agency.rb
class Agency < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_many :agency_groups
  has_many :groups, through: :agency_groups
  
  has_many :agents
  has_many :properties
  
 
  validates :email, presence: true

  after_create :create_agents


  def create_agents

  	director = Agent.create(first_name: "",
  		last_name: "",
  		email: "",
  		cellphone: "",
  		position_id: 1,
  		agency_id: self.id)

  	agent = Agent.create(first_name: "",
  		last_name: "",
  		email: "",
  		cellphone: "",
  		position_id: 2,
  		agency_id: self.id)

  end

  def available_properties
    self.properties.where(is_archived: false)
  end 

end

app/models/agency_group.rb
class AgencyGroup < ApplicationRecord
  belongs_to :group
  belongs_to :agency
end

app/models/agent.rb
class Agent < ApplicationRecord
  belongs_to :position
  belongs_to :agency
  has_many :properties

end

app/models/area.rb
class Area < ApplicationRecord
	has_many :properties
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :tenant
	belongs_to :property

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :agency_groups
  has_many :agencies, through: :agency_groups

  validates :name, presence: true
end

app/models/payment_status.rb
class PaymentStatus < ApplicationRecord
  has_many :tenants
end

app/models/position.rb
class Position < ApplicationRecord
  has_many :agents

  validates :title, 
    presence: true,
    uniqueness: true
end

app/models/property.rb
class Property < ApplicationRecord
	belongs_to :agent
	belongs_to :agency
	belongs_to :area

	has_many_attached :images
	has_many :visits

	has_many :favorites
	has_many :tenants, through: :favorites

	validates :title, 
	:surface, 
	:address, 
	:room, 
	:description, 
	:price, 
	:floor, 
	:available_date, presence: true

	validates :room, numericality: { only_integer: true }
	validates :price, numericality: { only_integer: true }
	validates :surface, numericality: true
	validates :floor, numericality: { only_integer: true }
	validates :description, length: { minimum: 40 }
	validates :title, length: { minimum: 10 }

	def self.not_archived
		self.where(is_archived: false)
	end 

	def total_rent
		self.price.to_i + self.charges.to_i
	end

	def existant_fav(tenant)
		Favorite.find_by(property_id: self.id, tenant: tenant)
	end

	def requested_visits(tenant)
		self.visits.where(visit_status_id: 4, tenant: tenant)
	end

	def requested_visits_agency
		self.visits.where(visit_status_id: 4, property: self)
	end

end

app/models/status.rb
class Status < ApplicationRecord
  has_many :visits
end

app/models/tenant.rb
class Tenant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  has_many :visits
  belongs_to :payment_status

  before_validation :default_payment_status

  has_many :favorites
  has_many :properties, through: :favorites

  has_one_attached :avatar

  before_create :attach_avatar

  def default_payment_status
    self.payment_status_id ||= 1
  end

  def fav_properties
    self.favorites.where(is_liked: true)
  end

  def asked_visits
    self.visits.where(visit_status_id: 4)
  end

  def successful_rent
    self.visits.where(visit_status_id: 6)
  end

  def attach_avatar
    self.avatar.attach(io: File.open('app/assets/images/avatar.png'), filename: 'avatar.png', content_type: 'image/png')
  end

  def existant_visit(property)
    visit = Visit.find_by(property_id: property.id, tenant: self)
    if visit
      return visit
    end
  end

  def unfav(property)
    favoris = Favorite.find_by(property_id: property.id, tenant: self, is_liked: true)
    unless favoris.nil?
      favoris.update_attributes(is_liked: false)
    end
  end


  def welcome_mail
    TenantMailer.welcome_email(self).deliver_now
  end

  def requested_visits
    self.visits.where(visit_status_id: 4)
  end

  def fav_properties
    self.favorites.where(is_liked: true)
  end

  def property_fav(property)
    self.favorites.where(property: property)
  end
end

app/models/visit.rb
class Visit < ApplicationRecord

	after_save :new_visit_email_send

  belongs_to :tenant
  belongs_to :property
  belongs_to :visit_status   

 	def new_visit_email_send
  	TenantMailer.new_visit_email(self.tenant, self.property).deliver_now
  end


end

app/models/visit_status 2.rb
class VisitStatus < ApplicationRecord
  has_many :visits
end

app/models/visit_status.rb
class VisitStatus < ApplicationRecord
  has_many :visits
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController


  before_action :authenticate_agency!
  before_action :is_current_agency?, only: [:show, :edit, :update]
  

  def index
  	@agencies = Agency.all
  end

  def show
  	@agency = current_agency
  	@properties = @agency.available_properties
    @director = @agency.agents.find_by(position_id: 1)
    @agent = @agency.agents.find_by(position_id: 2)
    @property = Property.new
    @areas = Area.all
  end

  # This method test if the agency is trying to access to an other agency profile page and redirect him to his own profile page if it is
  def is_current_agency?
    if params[:id]
      agency = Agency.find(params[:id])
      if agency != current_agency
        redirect_to agency_path(current_agency.id)
      end
    end
  end



end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/agencies/_edit_connexion_info.html.erb
<div class="viewport">
	<div class="image image-overlay" style="background-image:url(<%=asset_path('sofa.jpg')%>)"></div>


	<div class="container">
		<div class="row justify-content-center align-items-center vh-100">
			<div class="col-md-6 col-lg-5 white">




					<h3>Modifier mes infos de connexion</h3>
					<div class="mt-2 mb-2">
						<p>Vous souhaitez modifier votre adresse mail ou votre mot de passe ? <br> <a class="btn-orange text-white btn-sm" data-toggle="modal" data-target="#editInfos">
							Modifier mes infos de connexion
						</a> </p>
					</div>



					<div class="modal fade" id="editInfos" tabindex="-1" role="dialog" aria-labelledby="editInfosModal" aria-hidden="true">
						<div class="modal-dialog modal-dialog-centered" role="document">
							<div class="modal-content">
								<div class="modal-header justify-content-end">
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true" class="icon-x"></span>
									</button>
								</div>
								<div class="modal-body text-center">
									<h3>Modifier mes informations de connexion</h3>


									<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
									<%= f.error_notification %>

									<div class="form-inputs">

										<div class="form-group">
											<%= f.input :email,
											required: true,
											autofocus: true,
											input_html: { class: "form-control"  } %>
										</div>



										<% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
										<p>Currently waiting confirmation for: <%= resource.unconfirmed_email %></p>
										<% end %>
										<div class="form-group">
											<%= f.input :password,
											hint: "laisser vide si vous ne voulez pas le modifier",
											required: false,
											input_html: { autocomplete: "new-password", class: "form-control"  } %>
										</div>
										<div class="form-group">
											<%= f.input :password_confirmation,
											required: false,
											input_html: { autocomplete: "new-password", class: "form-control"  } %>
										</div>
										<div class="form-group">
											<%= f.input :current_password,
											hint: "Nous avons besoin de votre mot de passe actuel pour confirmer le changement",
											required: true,
											input_html: { autocomplete: "current-password", class: "form-control"  } %>
										</div>
									</div>


								</div>
								<div class="modal-footer">
									<%= f.button :submit, "Mettre à jour" %>
								</div>
								<% end %>
							</div>
						</div>
					</div>




					<h3>Supprimer mon compte</h3>

					<p>Vous souhaitez supprimer votre compte de notre plateforme ? <%= link_to "Supprimer mon compte", registration_path(resource_name), data: { confirm: "Etes vous sûr ?" }, method: :delete, class: 'btn-danger text-white btn-sm' %></p>

					<%= link_to "Revenir", agency_path(current_agency), class: "btn btn-primary" %>


			</div>
		</div>
	</div>
</div>

app/views/agencies/_login_registrar_form.html.erb
<div class="viewport">
  <div class="image image-overlay" style="background-image:url(<%=asset_path('sofa.jpg')%>)"></div>


<div class="container">
        <div class="row justify-content-center align-items-center vh-100">
          <div class="col-md-6 col-lg-5">
            <div class="accordion-group accordion-group-portal" data-accordion-group="">
              
              
              <div class="row  p-1 mb-0 bg-primary d-flex align-items-center">
                <div class="col-12 agency-login d-flex align-items-center justify-content-center">
                  Espace agence
                </div>
              </div>
              <!-- LOGIN -->
              <div class="accordion open" data-accordion="">
                <div class="accordion-control" data-control="">
                  <h5>Connexion</h5>
                </div>
                <div class="accordion-content" data-content="" style="transition: max-height 300ms ease 0s; max-height: 0px; overflow: hidden;">
                  <div class="accordion-content-wrapper">
                    <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                      <div class="form-group">
                        <%= f.input :email,
                          required: false,
                          autofocus: true,
                          input_html: { autocomplete: "email", class: "form-control" } %>
                        
                      <span style="opacity: 1; left: 392px; top: 151.5px; width: 19px; min-width: 19px; height: 13px; position: absolute; background-image: url(""); background-repeat: no-repeat; background-position: 0px 0px; border: none; display: inline; visibility: visible; z-index: auto;"></span>
                    </div>

                      <div class="form-group">
                        <%= f.input :password,
                          required: false,
                          input_html: { autocomplete: "current-password", class: "form-control"  } %>
                      <span style="opacity: 1; left: 392px; top: 249.5px; width: 19px; min-width: 19px; height: 13px; position: absolute; background-image: url(""); background-repeat: no-repeat; background-position: 0px 0px; border: none; display: inline; visibility: visible; z-index: auto;"></span></div>
                      

                      <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>



                      <%= f.button :submit, "Se connecter", class: "btn btn-primary btn-block" %>
                    <% end %>
                    
                      <%= render 'agencies/modal_reset_password'%>
                  </div>
                </div>
              </div>


            <!-- SIGNUP -->
<%#              <div class="accordion" data-accordion="">
                <div class="accordion-control" data-control="">
                  <h5>Créer un compte</h5>
                </div>
                <div class="accordion-content" data-content="" style="max-height: 382px; overflow: hidden; transition: max-height 300ms ease 0s;">
                  <div class="accordion-content-wrapper">
                    <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
<%#                      <%= f.error_notification %>
                     <!-- email -->
<%#                        <div class="form-group">
                        <%= f.input :email,
                          required: true,
                          autofocus: true,
                          input_html: { autocomplete: "email",
                          class: "form-control",}%>
<%#                        </div>
                      <!-- password -->
                      <div class="form-group">
                        <%= f.input :password,
                          required: true,
                          hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                          input_html: { autocomplete: "new-password", class: "form-control" } %>
<%#                        </div>
                      <div class="form-group">
                          <%= f.input :password_confirmation,
                            required: true,
                            input_html: { autocomplete: "new-password", class: "form-control" } %>
<%#                        </div>
                      <%= f.button :submit, "Créer un compte", class: "btn btn-primary btn-block" %>
<%#                      <% end %>
<%#                    </div>
                </div>
              </div>
            </div> %>
          </div>
        </div>
      </div>



</div>

app/views/agencies/_modal_reset_password.html.erb
<div class="mt-2 mb-2">
  <a class="text-primary link" data-toggle="modal" data-target="#forgotPassword">
    Mot de passe oublié ?
  </a>
</div>



<div class="modal fade" id="forgotPassword" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header justify-content-end">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" class="icon-x"></span>
        </button>
      </div>
      <div class="modal-body text-center">
        <h3>Mot de passe oublié ?</h3>
        <p>Renseigner votre mail ci-dessous afin de recevoir les instructions de rénitialisation de votre mot de passe</p>

        <%= simple_form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do |form| %>
        <%= form.error_notification %>

        

        <div class="form-inputs">
          <div class="form-group">
            <%= form.input :email,
            label: 'Votre email ',
            required: true,
            autofocus: true,
            input_html: { autocomplete: "email" },
            class: "form-control" %>
          </div>

        </div>


      </div>
      <div class="modal-footer">
        <%= form.button :submit, "Envoyer les instructions par mail", class: "btn btn-primary btn-block" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/agencies/_new_properties.html.erb
<div class="tab-pane" id="demo-2-2" role="tabpanel" aria-labelledby="demo-2-2">
  <div class="row justify-content-center">
    <div class="col-md-10 col-lg-8">
      <div class="row">
        <div class="col">

          <%= form_for [agency, property] do |f| %>
          <div class="form-row">
            <div class="col">
              <div class="form-group">
                <label for="userMail">Titre</label>
                <%= f.text_field :title, class: "form-control", placeholder:"T2 avec une incroyable vue" , required:true %>
              </div>
            </div>
          </div>
          <div class="form-row">
            <div class="col">
              <div class="form-group">
                <label for="firstName">Loyer H.C.</label>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-coins"></i></span>
                  </div>
                  <%= f.text_field :price, class: "form-control", placeholder:"1600 €" %>
                </div>
              </div>
            </div>
            <div class="col">
              <div class="form-group">
                <label for="firstName">Charges</label>
                <div class="input-group">
                  <%= f.text_field :charges, class: "form-control", placeholder:"100 €" %>
                </div>
              </div>
            </div>
          </div>
          <div class="form-row">
            <div class="col">
              <div class="form-group">
                <label for="firstName">Honoraires de location</label>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-money-check"></i></span>
                  </div>
                  <%= f.text_field :agency_fees, class: "form-control", placeholder:"500 €" %>
                </div>
              </div>
            </div>
            <div class="col">
              <div class="form-group">
                <label for="firstName">Dépôt de garantie</label>
                <div class="input-group">
                  <%= f.text_field :deposit, class: "form-control", placeholder:"500 €" %>
                </div>
              </div>
            </div>
          </div>


          <div class="form-row">
            <div class="col">
              <div class="form-group">
                <label for="firstName">Surface</label>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-arrows-alt-h"></i></span>
                  </div>
                  <%= f.text_field :surface, class: "form-control", placeholder:"75 m2" %>
                </div>
              </div>
            </div>
          </div>
          
          <div class="form-row">
            <div class="col">
              <div class="form-group">
                <label for="firstName">Etage</label>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fas fa-hiking"></i></span>
                  </div>
                  <%= f.number_field :floor, class: "form-control", placeholder:"3 ème" %>
                </div>
              </div>
            </div>



            <div class="col">
              <div class="form-group">
                <label for="secondName">Nombre de chambres</label>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fas fa-home"></i></span>
                  </div>
                  <%= f.number_field :room, class: "form-control", placeholder:"2" %>
                </div>
              </div>
            </div>

            <div class="col">
              <div class="form-group">
                <label for="secondName">Date de dispo.</label>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fas fa-calendar-alt"></i></span>
                  </div>
                  <%= f.date_field :available_date, class: "form-control", placeholder:"20/10/2020" , required:true%>
                </div>
              </div>
            </div>
          </div>



          <div class="form-row">
            <div class="col-6">
              <div class="form-group">
                <label for="agencyAddress">Addresse</label>
                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-map-marker-alt"></i></span>
                  </div>
                  <%= f.text_field :address, class: "form-control", placeholder:"68 Rue Joseph de Maistre" %>
                </div>
              </div>
            </div>
            <div class="col">
              <div class="form-group">
                <label for="firstName">Arrondissement</label>
                <select class="form-control" name="area" min-width="100px">
                  <%= @areas.each do |area| %>
                  <option><%= area.name %></option>
                  <% end %>
                </select>
              </div>
            </div>
          </div>

          <div class="form-row">
            <div class="col">
              <div class="form-group">
                <label for="exampleFormControlTextarea1">Description</label>
                <%= f.text_area :description, class: "form-control", placeholder:"Appartement meublé de 75 m², au 3ème étage d'un immeuble récent, se compose d'une entrée, d'un salon, d'une chambre, d'une salle de bains. Les WC sont séparés et une TERRASSE de 32 m² avec vue sur le Sacré Coeur complète ce bien. De nombreux placards. Les sols sont en marbre, très belles prestations. Chauffage et eau collectifs.", rows: "8" %>
              </div>
            </div>
          </div>



          <div class="form-row mt-1 align-items-center">
            <div class="col-8">
              <%= f.file_field :images, multiple: true , required:true, class:'inputfile' , id: 'images'%>
              <label for="images" class="btn btn-success btn-sm">Ajouter des photos</label>
            </div>
            <div class="col-3">
              <%= submit_tag("Enregistrer mon bien", id: "button", class: "btn btn-secondary", name: "submit") %>
            </div>
          </div>

          <% end %>


        </div>
      </div>
    </div>
  </div>
</div>

app/views/agencies/_profile.html.erb
<div class="tab-pane" id="demo-2-3" role="tabpanel" aria-labelledby="demo-2-3">
  <div class="row justify-content-center">
    <div class="col-md-10 col-lg-8">

      <div class="row">
        <div class="col">
          <%= link_to "Modifier les informations de connexion ou supprimer mon compte", edit_agency_registration_path %>
        </div>
      </div>


      <div class="row">
        <div class="col">
          <h5 class="mb-2 fs-20 font-weight-normal">Directeur de l'agence</h5>
          <%= form_for @director do |f| %>
            <div class="form-row">
              <div class="col">
                <div class="form-group">
                  <label for="directorFirstName">Prénom</label>
                   <%= f.text_field :first_name, class: "form-control", placeholder:"Louis", value: @director.first_name %>
                </div>
              </div>
              <div class="col">
                <div class="form-group">
                  <label for="directorSecondName">Nom</label>
                  <%= f.text_field :last_name, class: "form-control", placeholder:"Martin", value: @director.last_name %>
                </div>
              </div>
            </div>
            <div class="form-row">
              <div class="col">
                <div class="form-group">
                  <label for="directorMail">Email</label>
                  <%= f.email_field :email, class: "form-control", placeholder:"directeur@agence.com", value: @director.email %>
                </div>
              </div>
              <div class="col">
                <div class="form-group">
                  <label for="directorPhone">Téléphone</label>
                  <%= f.text_field :cellphone, class: "form-control", placeholder:"06.......", value: @director.cellphone %>
                </div>
              </div>
            </div>
            <div class="form-row mt-1 align-items-center">
              <div class="col-3">
                <button class="btn btn-secondary">Enregistrer</button>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <h5 class="mb-2 fs-20 font-weight-normal">Gestionnaire de l'agence</h5>
          <%= form_for @agent do |f| %>
            <div class="form-row">
              <div class="col">
                <div class="form-group">
                  <label for="agentFirstName">Prénom</label>
                   <%= f.text_field :first_name, class: "form-control", placeholder:"Jeanne", value: @agent.first_name %>
                </div>
              </div>
              <div class="col">
                <div class="form-group">
                  <label for="agentSecondName">Nom</label>
                   <%= f.text_field :last_name, class: "form-control", placeholder:"Dubois", value: @agent.last_name %>
                </div>
              </div>
            </div>
            <div class="form-row">
              <div class="col">
                <div class="form-group">
                  <label for="agentMail">Email</label>
                   <%= f.text_field :email, class: "form-control", placeholder:"agent@agence.com", value: @agent.email %>                </div>
              </div>
              <div class="col">
                <div class="form-group">
                  <label for="agentPhone">Téléphone</label>
                  <%= f.text_field :cellphone, class: "form-control", placeholder:"06.......", value: @agent.cellphone %>
                </div>
              </div>
            </div>
            <div class="form-row mt-1 align-items-center">
              <div class="col-3">
                <button class="btn btn-secondary">Enregistrer</button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/agencies/_show_properties.html.erb
 <div class="tab-pane show active" id="demo-2-1" role="tabpanel" aria-labelledby="demo-2-1">
	<div class="row justify-content-center">
	  <div class="col-md-12 col-lg-12">
	    <div class="row gutter-1 align-items-center">

		<% if properties.count == 0 %>

		  <div class="col-8">
		        <div class="boxed p-2 bordered scaling">
		          <div class="row align-items-center justify-content-between">
		            <div class="col-10">
								<h5>Vous n'avez aucune annonce en cours.</h5>
								<p>Pour ajouter une annonce, cliquez sur "Créer une annonce".</p>
								</div>
							</div>
						</div>
			</div>
		<% else %>
		<% properties.each do |property| %>

		    <div class="col-8">
		        <div class="boxed p-2 bordered scaling">
		          <div class="row align-items-center justify-content-between">
		            <div class="col-10">
			            <%= link_to agency_property_path(@agency,property) do %>
			              <div class="media align-items-center">
			                <img src="<%=asset_path(image_path(main_app.url_for(property.images.first)))%>" alt="Avatar" class="avatar avatar-lg mr-3">

			                <div class="media-body">
			                  <h5 class="mb-0"><%=property.title%></h5>
			                  <br>
			                  <container>
			                  	<div class="row">
				                  <div class="col-4 text-muted"><i class="fas fa-arrows-alt-h"></i> <%=property.surface%> m2  </div>
				                  <div class=" col-4 text-muted"><i class="fas fa-coins"></i> <%=property.price%> €  </div>
				                  <div class="col-4 text-muted"><i class="fas fa-map-marker-alt"></i> <%=property.area.zipcode%></div>
				              	</div>
			              	  </container>
			                </div>
			              </div>
			            <% end %>
		            </div>
		          </div>
		        </div>
		    </div>


				<div class="col-2 align-items-center ml-2">
					<div class="row ml-1 pt-2 mb-4">
						<div class="progress-item">
							<h4 class="progress-title">Demandes de visites</h4>
							<div class="progress">
								<%asked_visits = property.visits.length %>
									<div class="progress-bar bg-orange" role="progressbar" style="width: <%=asked_visits*10%>%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"><span class="text-orange"><%=asked_visits%></span></div>
							</div>
						</div>
					</div>
					<div class="row ml-1" >
						<div class="col-2" style="padding-left: -2em">
								<%= link_to "Voir l'annonce", agency_property_path(@agency,property), class: "btn btn-blue btn-sm" %>
						</div>
					</div>
				</div>
			<% end %>
		<% end %>

	    </div>
	  </div>
	</div>
</div>

app/views/agencies/index.html.erb
<h1>Agencies#index</h1>
<p>Find me in app/views/agencies/index.html.erb</p>